name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix with flakes support
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Verify Nix development environment
        run: |
          nix develop --command echo "✅ Nix environment works!"
      
      - name: Build hello-world project
        run: |
          nix develop --command make build PROJECT=hello-world
      
      - name: Run hello-world simulation test
        run: |
          nix develop --command make test-hello-world
      
      - name: Run comprehensive regression tests
        run: |
          nix develop --command make regression
